name: MS Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4.1.7

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build
        run: |
          msbuild /m /p:Configuration=Debug /p:Platform=x86
          msbuild /m /p:Configuration=Debug /p:Platform=x64
          msbuild /m /p:Configuration=Release /p:Platform=x86
          msbuild /m /p:Configuration=Release /p:Platform=x64
